CREATE TABLE IF NOT EXISTS review_trash(id TEXT PRIMARY KEY, removed_at TEXT NOT NULL, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS split_plans(id INTEGER PRIMARY KEY, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS independence_reviews(id INTEGER PRIMARY KEY CHECK(id=1), data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS annotation_blobs(hash TEXT PRIMARY KEY, shapes TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS history_asset_id ON history(asset_id);
