"""Prompted SAM2.1 image segmentation with optional lazy dependencies."""

from .backend import (
    HuggingFaceSam2Runtime,
    RuntimeFactory,
    Sam2RuntimeProtocol,
    Sam2Segmenter,
)
from .models import (
    Sam2Config,
    Sam2DependencyError,
    Sam2DeviceError,
    Sam2Diagnostics,
    Sam2Error,
    Sam2InferenceError,
    Sam2ModelLoadError,
    Sam2NoMaskError,
    Sam2RawOutput,
    Sam2SegmentationResult,
    Sam2WorkerState,
)
from .postprocess import (
    Sam2CandidateSelection,
    Sam2PromptEncoding,
    encode_sam2_prompts,
    extract_curvature_adaptive_contour_hierarchy,
    finalize_sam2_mask,
    keep_main_prompted_component,
    select_best_sam2_candidate,
    smooth_binary_mask,
)
from .layout_repair import (
    Sam2LayoutRepairPlan,
    find_misnamed_sam2_sessions,
    repair_misnamed_sam2_sessions,
)
from .training_dataset import (
    COCO_SCHEMA_VERSION,
    HUMAN_VERIFIED_REVIEW_STATUS,
    LABEL_SOURCE,
    MIXED_REVIEW_STATUS,
    REJECTED_REVIEW_STATUS,
    REVIEW_STATUS,
    SAMPLE_REVIEW_STATUSES,
    SESSION_REVIEW_STATUSES,
    TRAINING_MANIFEST_SCHEMA_VERSION,
    Sam2TrainingDatasetSession,
    Sam2TrainingSampleRecord,
    decode_coco_uncompressed_rle,
    encode_coco_uncompressed_rle,
)
from .worker import Sam2Worker, Sam2WorkerResult, SegmenterFactory


__all__ = [
    "HuggingFaceSam2Runtime",
    "COCO_SCHEMA_VERSION",
    "HUMAN_VERIFIED_REVIEW_STATUS",
    "LABEL_SOURCE",
    "MIXED_REVIEW_STATUS",
    "REJECTED_REVIEW_STATUS",
    "REVIEW_STATUS",
    "RuntimeFactory",
    "Sam2CandidateSelection",
    "Sam2Config",
    "Sam2DependencyError",
    "Sam2DeviceError",
    "Sam2Diagnostics",
    "Sam2Error",
    "Sam2InferenceError",
    "Sam2LayoutRepairPlan",
    "Sam2ModelLoadError",
    "Sam2NoMaskError",
    "Sam2PromptEncoding",
    "Sam2RawOutput",
    "Sam2RuntimeProtocol",
    "Sam2SegmentationResult",
    "Sam2Segmenter",
    "Sam2TrainingDatasetSession",
    "Sam2TrainingSampleRecord",
    "Sam2Worker",
    "Sam2WorkerResult",
    "Sam2WorkerState",
    "SAMPLE_REVIEW_STATUSES",
    "SESSION_REVIEW_STATUSES",
    "SegmenterFactory",
    "TRAINING_MANIFEST_SCHEMA_VERSION",
    "decode_coco_uncompressed_rle",
    "encode_coco_uncompressed_rle",
    "encode_sam2_prompts",
    "extract_curvature_adaptive_contour_hierarchy",
    "find_misnamed_sam2_sessions",
    "finalize_sam2_mask",
    "keep_main_prompted_component",
    "repair_misnamed_sam2_sessions",
    "select_best_sam2_candidate",
    "smooth_binary_mask",
]
